### ISSUE TITLE
can not run by source code under vscode

### ISSUE THREAD

**Issue by beanslee2012** [boomxch/StreamingWidget#5]
Hi,

I tried to compile and run using the source code, but I encountered the following two windows and I can't login by my nintendo id:

 
![image](https://user-images.githubusercontent.com/3379460/127132589-4f216c80-f3a7-460b-a237-d44f3dcff503.png)
![image](https://user-images.githubusercontent.com/3379460/127132618-8a902699-1df7-47ec-876d-672937c950cb.png)

Then I clicked the update button and it runs the downloaded version instead of the source code version.

when I cancled the update window and login by my nintendo account uri,then I got these error:

Unhandled exception. System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request)
   at Splatoon2StreamingWidget.HttpManager.GetAutoDeserializedJsonAsync[TJson](HttpRequestMessage request) in D:\game\ns\splatoon\StreamingWidget-Ver1.2.9\Splatoon2StreamingWidget\HttpManager.cs:line 34
   at Splatoon2StreamingWidget.SplatNet2SessionToken.GetSessionToken(String sessionTokenCode, String authCodeVerifier) in D:\game\ns\splatoon\StreamingWidget-Ver1.2.9\Splatoon2StreamingWidget\SplatNet2SessionToken.cs:line 91
   at Splatoon2StreamingWidget.MainWindow.UpdateSessionButton_Click(Object sender, RoutedEventArgs e) in D:\game\ns\splatoon\StreamingWidget-Ver1.2.9\Splatoon2StreamingWidget\MainWindow.xaml.cs:line 266
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

=============
 so I guess whether the code is not the latest？

thanks!!!

**Comment by boomxch** [comment]
Sorry.
In my source code, I have left out some information (mainly URLs related to the login mechanism for obtaining session tokens).
This is because the login service I use in my application was created by a volunteer and cannot be used without prior inquiry.
I am releasing the source code without these URLs because the main purpose of releasing the source code is to ensure some transparency of the application and to make it easier to receive advice on updating the source code.
I'm sorry for any inconvenience this may cause.

**Comment by beanslee2012** [comment]
Okay, I get it. 
Thank you for the great projects!
